version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: aminofabian
      POSTGRES_PASSWORD: cov1d$5mOvld
      POSTGRES_DB: mediamasses
      PGDATA: /var/lib/postgresql/data/pgdata/

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://aminofabian:cov1d$5mOvld@db:5432/mediamasses
    depends_on:
      - db

volumes:
  postgres_data:




