# version: '3.8'
# services:
#   db:
#     container_name: mediamasses_app_postgres_dev
#     image: postgres:13
#     environment:
#       POSTGRES_USER: aminofabian
#       POSTGRES_PASSWORD: cov1d$5mOvld
#       POSTGRES_DB: mediamasses
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U aminofabian -d mediamasses"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

#   web:
#     build: .
#     ports:
#       - "3000:3000"
#     environment:
#       - DATABASE_URL=postgresql://aminofabian:cov1d$5mOvld@db:5432/mediamasses?schema=public
#     depends_on:
#       db:
#         condition: service_healthy

# volumes:
#   postgres_data:


# version: '3.8'
# services:
#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: aminofabian
#       POSTGRES_PASSWORD: cov1d5mOvld
#       POSTGRES_DB: mediamasses
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:


version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  postgres-data: