name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH and rsync
        run: sudo apt-get install -y sshpass

      - name: Prepare server directory and Sync files
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          ENV_FOLDER="mediamasses-$(echo $GITHUB_REF | sed 's/refs\/heads\///')"
          sshpass -p $SERVER_PASSWORD ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_IP "mkdir -p /var/www/$ENV_FOLDER && chown -R root:root /var/www/$ENV_FOLDER && chmod -R 755 /var/www/$ENV_FOLDER"
          sshpass -p $SERVER_PASSWORD rsync -av --rsh="ssh -o StrictHostKeyChecking=no" ./ $SERVER_USERNAME@$SERVER_IP:/var/www/$ENV_FOLDER

      - name: Deploy using Docker Compose
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          ENV_FOLDER="mediamasses-$(echo $GITHUB_REF | sed 's/refs\/heads\///')"
          if [[ $GITHUB_REF == 'refs/heads/prod' ]]; then
            DOCKER_COMPOSE_FILE=docker-compose-production.yml
          else
            DOCKER_COMPOSE_FILE=docker-compose-development.yml
          fi
          sshpass -p $SERVER_PASSWORD ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_IP << EOF
            cd /var/www/$ENV_FOLDER
            docker compose -f $DOCKER_COMPOSE_FILE down
            docker compose -f $DOCKER_COMPOSE_FILE up --build -d
          EOF

      - name: Check Container Status
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          ENV_FOLDER="mediamasses-$(echo $GITHUB_REF | sed 's/refs\/heads\///')"
          if [[ $GITHUB_REF == 'refs/heads/prod' ]]; then
            DOCKER_COMPOSE_FILE=docker-compose-production.yml
          else
            DOCKER_COMPOSE_FILE=docker-compose-development.yml
          fi
          sshpass -p $SERVER_PASSWORD ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_IP << EOF
            cd /var/www/$ENV_FOLDER
            docker-compose -f $DOCKER_COMPOSE_FILE ps
          EOF
